### PR TITLE
Change the image addr to match the new image-hub's namespace.

### PR DESCRIPTION
**Pull request by Summer-Field**
As a consequence of new volcengine account, the image hub's address has changed. So, I update the new url of the image addr.

### CODE REVIEW

**Review by Jeffwan — APPROVED** [review]

**Comment by Jeffwan** [comment]
@Summer-Field Let's start to use prow to merge the changes. If it doesn't work, please help figure out the root cause

**Comment by Summer-Field** [comment]
> @Summer-Field Let's start to use prow to merge the changes. If it doesn't work, please help figure out the root cause

OK

**Pull request merged**
