### PR TITLE
Add command for both gitops periodic jobs

### PR DESCRIPTION
**Pull request by Summer-Field**
Add command for both gitops periodic jobs

### CODE REVIEW

**Comment by Summer-Field** [comment]
There is one more things we need to discuss:
- What the interval/schedule time should we set to those jobs? Like 30min? 1h? 24h? Now, We set the same config for both of the gitops periodic job with `cron "17 * * * *"`. However, The upstream set `cron "17 * * * *"` for `label_sync` and `interval 24h` for `peribolos`. 
[Here is the upstream config](https://github.com/kubernetes/test-infra/blob/b2eedbd498292f1567f6df03c3c44e765acbd521/config/jobs/kubernetes/test-infra/test-infra-trusted.yaml)

/cc @Jeffwan

**Comment by Jeffwan** [comment]
Let's flush the configs every 12hr? WDTY?

**Comment by Jeffwan** [comment]
schedule time is flexible. It could be anytime. I think we only care about the interval.

**Comment by Summer-Field** [comment]
> schedule time is flexible. It could be anytime. I think we only care about the interval.

Yes, I agree.

> Let's flush the configs every 12hr? WDTY?

I'm not sure... How about setting the interval as 12h first, and adjust it according to org members' feedback.

**Comment by Jeffwan** [comment]
@Summer-Field I don't think member will give opinions on this setting. we can make the decision. Let's change to interval 12h to replace `cron`

**Comment by Jeffwan** [comment]
I will approve this one first. You can file a separate PR to update interval

**Review by Jeffwan — APPROVED** [review]

**Comment by Summer-Field** [comment]
> I will approve this one first. You can file a separate PR to update interval

Done: https://github.com/kitex-contrib/test-infra/pull/47

**Pull request merged**
