### PR TITLE
Convert cncf-cla to bytedance-cla

### PR DESCRIPTION
**Pull request by Summer-Field**
Convert cncf-cla to bytedance-cla

### CODE REVIEW

**Comment by Jeffwan** [comment]
I thought we didn't enable cla plugin and this should not be applied?

**Comment by Summer-Field** [comment]
> I thought we didn't enable cla plugin and this should not be applied?

I just think that we need a cla label for bytedance instead of `cncf cla`. Maybe we could write our own cla_bytedance plugin in the future.

**Comment by Summer-Field** [comment]
Why it takes such a long period time to enable ci-robot...

Let me figure out the cause...

**Pull request closed without merging**
